title: Deepfake as a Disruptive Technology
description: A web report by Group H of MMS 142 A.Y. 2022-2023 1st Trimester.
show_downloads: true
google_analytics:
markdown: kramdown
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false

header_pages:
  - article
  - article1
  - article 4
  - deepfakes
